
name: 'Dependency Review'
on: 
  push:
    branches: [ "master" ]
  

   schedule:
    - cron: '42 21 * * 2'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read

jobs:

  Trigger_APIsec_scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest

    steps:
       - name: APIsec scan
         uses: apisec-inc/apisec-run-scan@f748a240d69ca6cd7e9532fd0a47bec4ccd6a73c
         with:
         
          apisec-username: ${{ secrets.apisec_username }}
          
          apisec-password: ${{ secrets.apisec_password}}
          
          apisec-project: "VAmPI"
          
          sarif-result-file: "apisec-results.sarif"
       - name: Import results
         uses: github/codeql-action/upload-sarif@v2
         with:
          sarif_file: ./apisec-results.sarif


      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      
